# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

title: Dr Hobo's Blog
description: The official blog of Dr Hobo (thedrhobo), featuring top 10 lists on film, games, music, books, and more.
author: Dr Hobo
baseurl: ""
url: "https://thedrhobo.github.io"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
