# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Films', url: '/top-10-films'}
- {name: 'Books', url: '/top-10-books'}
- {name: 'Music', url: 'menu/music.html'}
- {name: 'Video Games', url: 'menu/videogames.html'}
- {name: 'Board Games', url: 'menu/boardgames.html'}
- {name: 'Travel', url: 'menu/travel.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    ''}
- {icon: 'facebook', link:   ''}
- {icon: 'instagram', link:  'https://www.instagram.com/iconicinkscapes/'}
- {icon: 'envelope', link:   'mailto:TheDrHobo@proton.me'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
